# gradle build

#http://jekyllrb.com/docs/configuration/

# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#

# Title of your website
title: "TWiStErRob"


# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "Professional & Hobby Development site"


# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Home for all things about and by Róbert&nbsp;Papp (TWiStErRob)."

# Main author of the website
# See > authors.yml
author: twisterrob

# This URL is the main address for absolute links. Don't include a slash at the end.
url: 'https://www.twisterrob.net'
baseurl: ''

# This is for the editing function in _/includes/improve_content.html
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/twisterrob/twisterrob.github.io/issues

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. Don't include a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: '/images/'

# Logo size is 600x80 pixels
logo: "logo-600x80.png"

# !github-pages! mandatory › https://github.com/github/pages-gem/blob/jekyll-v3-4-2/lib/github-pages/plugins.rb#L19-L37
# Also see https://github.com/github/pages-gem/issues/208
whitelist:
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji

plugins:
# !github-pages! optional › https://github.com/github/pages-gem/blob/jekyll-v3-4-2/lib/github-pages/plugins.rb#L6-L16
# paginate and paginate_path in _config is used
  - jekyll-paginate
# !github-pages! optional › https://help.github.com/articles/configuring-jekyll/
# Provides redirect_from: in frontmatter for path aliases
  - jekyll-redirect-from

#      _____ __                  __
#     / ___// /________  _______/ /___  __________
#     \__ \/ __/ ___/ / / / ___/ __/ / / / ___/ _ \
#    ___/ / /_/ /  / /_/ / /__/ /_/ /_/ / /  /  __/
#   /____/\__/_/   \__,_/\___/\__/\__,_/_/   \___/
#
# Open _data/navigation.yml to adjust the left and right topbar navigation
# Open _data/socialmedia.yml to adjust the left and right topbar navigation

show_drafts: null
limit_posts: 0
future:      true
unpublished: false
# Paginates all X entries
paginate: 10
# Pagination path › Important for blog page in /blog/ to work
paginate_path: "/blog/page:num/"

# !github-pages! mandatory › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
# Disables custom plugins and ignore symbolic links
# This means that ```java will not work because it requires https://github.com/mvdbos/kramdown-with-pygments
safe: true
# !github-pages! mandatory provided › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
#source: '.' # auto-set

# Include/Exclude these files from production _site
include: ['.htaccess']

# . files and folders are excluded by default,
# but --watch and serve are regenerating if they're not explicitly excluded.
# See › https://github.com/jekyll/jekyll/issues/3913
exclude:
  # GitHub
  - .git
  - .github
  - .gitignore
  - CNAME
  - README.md
  # Build Artifacts and byproducts
  - .sass-cache
  - .gradle
  - _site
  - _drafts/_*
  # Build Scripts and Dependencies
  - build.gradle
  - gradle
  - gradlew
  - gradlew.bat
  - Gemfile
  - Gemfile.lock
  # Workaround for GitHub actions Ruby action vs Jekyll v3.x
  - vendor/bundle
  # _config*.yml      # doesn't work, see https://github.com/jekyll/jekyll-watch/issues/34
  - _config_local.yml # need to explicitly exclude all configs https://github.com/jekyll/jekyll-watch/issues/35
  - _config_dev.yml   # need to explicitly exclude all configs https://github.com/jekyll/jekyll-watch/issues/35
  # Projects Files
  - .idea
  - www.twisterrob.net.ipr # should be '*.ipr', see https://github.com/jekyll/jekyll-watch/issues/34
  - www.twisterrob.net.iws # should be '*.ipr', see https://github.com/jekyll/jekyll-watch/issues/34
  - www.twisterrob.net.iml # should be '*.ipr', see https://github.com/jekyll/jekyll-watch/issues/34
  - .classpath
  - .project
  - www.twisterrob.net.sublime-project # should be '*.sublime-project', see https://github.com/jekyll/jekyll-watch/issues/34
  # Random stuff
  - sources
  - .svn
  - .git
  - System Volume Information

#       ______                                _
#      / ____/___  ____ _   _____  __________(_)___  ____
#     / /   / __ \/ __ \ | / / _ \/ ___/ ___/ / __ \/ __ \
#    / /___/ /_/ / / / / |/ /  __/ /  (__  ) / /_/ / / / /
#    \____/\____/_/ /_/|___/\___/_/  /____/_/\____/_/ /_/
#
quiet: false
excerpt_separator: "<!--more-->"

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  auto_ids:       true
  auto_id_stripping: true # TODO is this --safe?
  #transliterated_header_ids: true # requires some more dependency
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  toc_panel:      true
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  hard_wrap:      false
  # !github-pages! mandatory › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge
  # !github-pages! mandatory › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
  math_engine: mathjax
  show_warnings: true

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    #debug: false
    #parent: ''
    # Affects <pre class>, but not <div class> around <pre>
    # disabled to prevent problems with CSS due to .highlight > .highlight structure
    css_class: ''
    default_lang: text
    disable: false
    span:
      disable: false
    block:
      #wrap: true
      #line_numbers: true
      #start_line: 1
      disable: false

# More › http://sass-lang.com
# Docs › http://jekyllrb.com/docs/assets/#sassscss
# Options › http://sass-lang.com/documentation/file.SASS_REFERENCE.html#options
# Safe mode only allows style, syntax=based on extension, cache=false
sass:
  sass_dir: _sass
  # Options › http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :compressed # :nested | :expanded | :compact | :compressed

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  startings: []
  endings: all
  blanklines: false
  profile: false
  ignore:
    envs: [development]

# !github-pages! mandatory › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
incremental: false
# !github-pages! mandatory › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
# TODO what is this?
lsi: false


# The language setting is used in /includes/header.html for html-settings
language: "en"


# Docs › http://jekyllrb.com/docs/collections/
permalink: /blog/:year/:month/:title.html
collections:
  projects:
    output: true
    permalink: /project/:name/
  jobs:
    output: true
    permalink: /work/:name/
#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      #skip_boilerplate: true
  -
    scope:
      type: pages
      path: ''
    values:
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      show_meta:
        sharer: true
  -
    scope:
      type: posts
      path: ''
    values:
      show_meta:
        info: true
        sharer: true
        navigation: 'snippets/lateral_navigation_blog.html'
        comments: true
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      #author: twisterrob # disable for now, I'm the only one
  -
    scope:
      type: projects
      path: ''
    values:
      layout: project
      title_suffix: "a project by Róbert Papp (TWiStErRob)"
      published: true
      released: true
      breadcrumbs: true
      images:
        icon: projects/unknown-app-icon-512.png
        icon_small: projects/unknown-app-icon-512.png
      show_meta:
        info: true
        sharer: true
        comments: true
  -
    scope:
      type: jobs
      path: ''
    values:
      layout: job
      title_suffix: "a former workplace of Róbert Papp"
      breadcrumbs: true
      show_meta:
        sharer: true
        navigation: 'snippets/lateral_navigation_job.html'
  -
    scope:
      path: 'blog/category'
    values:
      #permalink: /blog/:category/ # will be available in 3.0, see https://github.com/jekyll/jekyll/pull/3320
      layout: blog_by_category
      breadcrumbs: true
      title_suffix: "category details"
      show_meta:
        sharer: true
        comments: true


#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

google_author:             "https://plus.google.com/+RóbertPappTWiStErRob"
#google_site_verification:  "Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ"
#bing_webmastertools_id:    "0FB4C028ABCF07C908C54386ABD2D97F"
# alexa_verify_id:         ""

# Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
# More information Â» https://mathiasbynens.be/notes/touch-icons
#favicon-32x32:                          "favicon-32x32.png"
#touch-icon-192x192:                     "touch-icon-192x192.png"
#apple-touch-icon-180x180-precomposed:   "apple-touch-icon-180x180-precomposed.png"
#apple-touch-icon-152x152-precomposed:   "apple-touch-icon-152x152-precomposed.png"
#apple-touch-icon-144x144-precomposed:   "apple-touch-icon-144x144-precomposed.png"
#apple-touch-icon-120x120-precomposed:   "apple-touch-icon-120x120-precomposed.png"
#apple-touch-icon-114x114-precomposed:   "apple-touch-icon-114x114-precomposed.png"
#apple-touch-icon-76x76-precomposed:     "apple-touch-icon-76x76-precomposed.png"
#apple-touch-icon-72x72-precomposed:     "apple-touch-icon-72x72-precomposed.png"
#apple-touch-icon-precomposed:           "apple-touch-icon-precomposed.png"
#msapplication_tileimage:                "msapplication_tileimage.png"               # Size 144x144
#msapplication_tilecolor:                "#fabb00"

# Facebook-Optimization › http://j.mp/fb_optimize
og_image:                           imgurl + "/logo-512x512.png"
og_locale:                          "en_EN"
og_type:                            "website"
#og_title:                           ""
#og_description:                     ""
#og_url:                             ""
#og_site_name:                       ""

#       ____      __                        __  _
#      /  _/___  / /____  ____ __________ _/ /_(_)___  ____
#      / // __ \/ __/ _ \/ __ `/ ___/ __ `/ __/ / __ \/ __ \
#    _/ // / / / /_/  __/ /_/ / /  / /_/ / /_/ / /_/ / / / /
#   /___/_/ /_/\__/\___/\__, /_/   \__,_/\__/_/\____/_/ /_/
#                      /____/
#
# Used › _includes/comments.html
disqus_shortname: twisterrob

# More › https://www.google.com/analytics/
# Used › _includes/footer_scripts.html
google_analytics_tracking_id: UA-38202353-4

# More › https://www.tawk.to/knowledgebase/
#        tawk.to is a free live chat app that lets you monitor and chat
#         with visitors on your website or from a free customizable page
#         To load the script add tawkto: true in front matter of each page
# Used › _includes/footer_scripts.html
#tawkto_embed_uri: https://embed.tawk.to/<id>/default<script>

gist:
  # !github-pages! mandatory › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
  noscript: false

# !github-pages! provided › https://help.github.com/articles/repository-metadata-on-github-pages/
# See local override for testing data
github:
  - stuff
